#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionesAppAccesoDatos.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="INSCRIPCIONES_APP_BD")]
	public partial class ConexionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ConexionDataContext() : 
				base(global::InscripcionesAppAccesoDatos.Properties.Settings.Default.INSCRIPCIONES_APP_BDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PS_GET_INSCRIPCIONES")]
		public ISingleResult<PS_GET_INSCRIPCIONESResult> PS_GET_INSCRIPCIONES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RESULTADO", DbType="Bit")] ref System.Nullable<bool> rESULTADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LISTA_ACIERTOS", DbType="NVarChar(MAX)")] ref string lISTA_ACIERTOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LISTA_ERRORES", DbType="NVarChar(MAX)")] ref string lISTA_ERRORES, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REGISTRO_ID", DbType="Int")] ref System.Nullable<int> rEGISTRO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rESULTADO, lISTA_ACIERTOS, lISTA_ERRORES, rEGISTRO_ID, eRROR_ID);
			rESULTADO = ((System.Nullable<bool>)(result.GetParameterValue(0)));
			lISTA_ACIERTOS = ((string)(result.GetParameterValue(1)));
			lISTA_ERRORES = ((string)(result.GetParameterValue(2)));
			rEGISTRO_ID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((ISingleResult<PS_GET_INSCRIPCIONESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PS_GET_CORREOS")]
		public ISingleResult<PS_GET_CORREOSResult> PS_GET_CORREOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RESULTADO", DbType="Bit")] ref System.Nullable<bool> rESULTADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LISTA_ACIERTOS", DbType="NVarChar(MAX)")] ref string lISTA_ACIERTOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LISTA_ERRORES", DbType="NVarChar(MAX)")] ref string lISTA_ERRORES, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REGISTRO_ID", DbType="Int")] ref System.Nullable<int> rEGISTRO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rESULTADO, lISTA_ACIERTOS, lISTA_ERRORES, rEGISTRO_ID, eRROR_ID);
			rESULTADO = ((System.Nullable<bool>)(result.GetParameterValue(0)));
			lISTA_ACIERTOS = ((string)(result.GetParameterValue(1)));
			lISTA_ERRORES = ((string)(result.GetParameterValue(2)));
			rEGISTRO_ID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((ISingleResult<PS_GET_CORREOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PS_INSERT_INSCRIPCION")]
		public int PS_INSERT_INSCRIPCION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="NVarChar(100)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO_1", DbType="NVarChar(100)")] string aPELLIDO_1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO_2", DbType="NVarChar(100)")] string aPELLIDO_2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GRADO", DbType="NVarChar(20)")] string gRADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECCION", DbType="NVarChar(10)")] string sECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="NVarChar(250)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONFIRMADO", DbType="Bit")] System.Nullable<bool> cONFIRMADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RESULTADO", DbType="Bit")] ref System.Nullable<bool> rESULTADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LISTA_ACIERTOS", DbType="NVarChar(MAX)")] ref string lISTA_ACIERTOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LISTA_ERRORES", DbType="NVarChar(MAX)")] ref string lISTA_ERRORES, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REGISTRO_ID", DbType="Int")] ref System.Nullable<int> rEGISTRO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERROR_ID", DbType="Int")] ref System.Nullable<int> eRROR_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, aPELLIDO_1, aPELLIDO_2, gRADO, sECCION, cORREO, cONFIRMADO, rESULTADO, lISTA_ACIERTOS, lISTA_ERRORES, rEGISTRO_ID, eRROR_ID);
			rESULTADO = ((System.Nullable<bool>)(result.GetParameterValue(7)));
			lISTA_ACIERTOS = ((string)(result.GetParameterValue(8)));
			lISTA_ERRORES = ((string)(result.GetParameterValue(9)));
			rEGISTRO_ID = ((System.Nullable<int>)(result.GetParameterValue(10)));
			eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(11)));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class PS_GET_INSCRIPCIONESResult
	{
		
		private int _INSCRIPCION_ID;
		
		private string _NOMBRE;
		
		private string _APELLIDO_1;
		
		private string _APELLIDO_2;
		
		private string _GRADO;
		
		private string _SECCION;
		
		private string _CORREO;
		
		private System.DateTime _FECHA_REGISTRO;
		
		private bool _CONFIRMADO;
		
		public PS_GET_INSCRIPCIONESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSCRIPCION_ID", DbType="Int NOT NULL")]
		public int INSCRIPCION_ID
		{
			get
			{
				return this._INSCRIPCION_ID;
			}
			set
			{
				if ((this._INSCRIPCION_ID != value))
				{
					this._INSCRIPCION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO_1", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string APELLIDO_1
		{
			get
			{
				return this._APELLIDO_1;
			}
			set
			{
				if ((this._APELLIDO_1 != value))
				{
					this._APELLIDO_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO_2", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string APELLIDO_2
		{
			get
			{
				return this._APELLIDO_2;
			}
			set
			{
				if ((this._APELLIDO_2 != value))
				{
					this._APELLIDO_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRADO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string GRADO
		{
			get
			{
				return this._GRADO;
			}
			set
			{
				if ((this._GRADO != value))
				{
					this._GRADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECCION", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string SECCION
		{
			get
			{
				return this._SECCION;
			}
			set
			{
				if ((this._SECCION != value))
				{
					this._SECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REGISTRO
		{
			get
			{
				return this._FECHA_REGISTRO;
			}
			set
			{
				if ((this._FECHA_REGISTRO != value))
				{
					this._FECHA_REGISTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONFIRMADO", DbType="Bit NOT NULL")]
		public bool CONFIRMADO
		{
			get
			{
				return this._CONFIRMADO;
			}
			set
			{
				if ((this._CONFIRMADO != value))
				{
					this._CONFIRMADO = value;
				}
			}
		}
	}
	
	public partial class PS_GET_CORREOSResult
	{
		
		private int _CORREO_ID;
		
		private string _CORREO;
		
		public PS_GET_CORREOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_ID", DbType="Int NOT NULL")]
		public int CORREO_ID
		{
			get
			{
				return this._CORREO_ID;
			}
			set
			{
				if ((this._CORREO_ID != value))
				{
					this._CORREO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
