USE INSCRIPCIONES_APP_BD;
GO

-- Tabla BITACORA
CREATE TABLE TB_BITACORA (
    BITACORA_ID INT IDENTITY(1,1) PRIMARY KEY,
    TABLA_NOMBRE NVARCHAR(100) NOT NULL,
    ACCION NVARCHAR(20) NOT NULL, -- INSERT / UPDATE / DELETE
    REGISTRO_ID NVARCHAR(100) NULL,
    LUGAR NVARCHAR(100) NULL,
    FECHA DATETIME NOT NULL DEFAULT GETDATE(),
    DETALLE NVARCHAR(MAX) NULL
);
GO

-- Tabla ERRORES
CREATE TABLE TB_ERRORES (
    ERROR_ID INT IDENTITY(1,1) PRIMARY KEY,
    FECHA DATETIME NOT NULL DEFAULT GETDATE(),
    ORIGEN NVARCHAR(200) NULL,
    MENSAJE NVARCHAR(MAX) NULL,
    PROCEDIMIENTO NVARCHAR(200) NULL,
    STACK_TRACE NVARCHAR(MAX) NULL
);
GO

-- Tabla INSCRIPCIONES
CREATE TABLE TB_INSCRIPCIONES (
    INSCRIPCION_ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    APELLIDO_1 NVARCHAR(100) NOT NULL,
    APELLIDO_2 NVARCHAR(100) NOT NULL ,
    GRADO NVARCHAR(20) NOT NULL,
    SECCION NVARCHAR(10) NOT NULL,
    CORREO NVARCHAR(250) NOT NULL UNIQUE,
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT GETDATE(),
    CONFIRMADO BIT NOT NULL
);
GO

-- Tabla CORREOS DESTINO
CREATE TABLE TB_CORREOS_DESTINO (
    CORREO_ID INT IDENTITY(1,1) PRIMARY KEY,
    CORREO NVARCHAR(250) NOT NULL
);
GO