USE INSCRIPCIONES_APP_BD;
GO

-- Trigger: AFTER INSERT INSCRIPCIONES
CREATE TRIGGER TR_INSCRIPCIONES_AFTER_INSERT
ON [dbo].[TB_INSCRIPCIONES]
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TB_BITACORA (TABLA_NOMBRE, ACCION, REGISTRO_ID, LUGAR, DETALLE)
    SELECT 'TB_INSCRIPCIONES','INSERT', CAST(I.INSCRIPCION_ID AS NVARCHAR(100)), 'TR_INSCRIPCIONES_AFTER_INSERT',
           CONCAT(
            '{',
                '"INSCRIPCION_ID":', CAST(I.INSCRIPCION_ID AS NVARCHAR(10)), ',',
                '"NOMBRE":"', I.NOMBRE, '",',
                '"APELLIDO_1":"', I.APELLIDO_1, '",',
                '"APELLIDO_2":"', I.APELLIDO_2, '",',
                '"GRADO":"', I.GRADO, '",',
                '"SECCION":"', I.SECCION, '",',
                '"CORREO":"', I.CORREO, '",',
                '"FECHA_REGISTRO":"', CAST(I.FECHA_REGISTRO AS NVARCHAR(50)), '",',
                '"CONFIRMADO":"', CAST(I.CONFIRMADO AS NVARCHAR(5)), '"',
            '}'
             )
    FROM INSERTED I;
END
GO

-- Trigger: AFTER INSERT CORREOS DESTINO
CREATE TRIGGER TR_CORREOS_DESTINO_AFTER_INSERT
ON TB_CORREOS_DESTINO
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TB_BITACORA (TABLA_NOMBRE, ACCION, REGISTRO_ID, LUGAR, DETALLE)
    SELECT 'TB_CORREOS_DESTINO','INSERT', CAST(I.CORREO_ID AS NVARCHAR(100)), 'TR_CORREOS_DESTINO_AFTER_INSERT',
            CONCAT(
                    '{',
                        '"CORREO_ID":', CAST(I.CORREO_ID AS NVARCHAR(10)), ',',
                        '"CORREO":"', I.CORREO, '"',
                    '}'
                )
    FROM INSERTED I;
END
GO